/**
 * Outbox repository — the interface.
 *
 * ── Why the interface is a separate file from the implementation ───────────
 * ADR-0010 says repository interfaces are owned by the domain and
 * implementations live here. `@platform/domain` does not exist yet — it arrives
 * with the producer in Chapter 4 — so the interface temporarily lives in this
 * package. Keeping it in its own file means that move is a `git mv`, not
 * surgery on a file that also contains SQL.
 *
 * The rule that must survive the move: **this file may not import `pg`.** If it
 * ever needs to, the abstraction has failed and the domain has become coupled
 * to the driver, which is the specific outcome ADR-0010 exists to prevent.
 *
 * ── What the outbox is for ─────────────────────────────────────────────────
 * The dual-write problem (ADR-0007): a service that updates its database and
 * then publishes to Kafka has two operations with no shared transaction. Crash
 * between them and the state changed but nobody was told — a silent, permanent
 * inconsistency that no retry can detect because the process that would have
 * retried is gone.
 *
 * The outbox makes them one operation: the event row is written in the *same*
 * transaction as the state change, and a separate relay publishes it
 * afterwards. The failure mode becomes "published late" or "published twice",
 * both of which the platform already handles.
 */

/** An event to be written inside the caller's transaction. */
export interface NewOutboxEvent {
  /**
   * Business identity, generated by the caller — **not** by the database.
   *
   * This is the idempotency key the consumer deduplicates on (ADR-0008), so it
   * must be stable across a relay retry. Deriving it from business meaning
   * (`order-placed:{orderId}:{version}`) rather than from delivery position
   * (`partition:offset`) is what makes a replay safe.
   */
  readonly eventId: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly eventType: string;
  readonly topic: string;
  /** Determines the Kafka partition, hence ordering. Omit when order does not matter. */
  readonly partitionKey?: string | undefined;
  readonly payload: Record<string, unknown>;
  readonly headers?: Record<string, string> | undefined;
  readonly correlationId?: string | undefined;
  readonly tenantId?: string | undefined;
}

/** A claimed row, ready to publish. */
export interface OutboxRecord {
  /**
   * `bigint`, not `number`.
   *
   * The column is `bigint` and `pg` returns int8 as a **string** by default,
   * precisely because values above 2^53 lose precision as JS numbers. Silently
   * parsing to `number` works for years and then starts corrupting IDs. The
   * type here forces every consumer to acknowledge that.
   */
  readonly id: bigint;
  readonly eventId: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly eventType: string;
  readonly topic: string;
  readonly partitionKey: string | null;
  readonly payload: Record<string, unknown>;
  readonly headers: Record<string, string>;
  readonly createdAt: Date;
  readonly attempts: number;
  readonly correlationId: string | null;
  readonly tenantId: string | null;
}

/** Where an event actually landed. Recorded so support can trace one event. */
export interface PublishOutcome {
  readonly id: bigint;
  readonly partition: number;
  readonly offset: bigint;
}

export interface OutboxRepository {
  /** Write one event. Must be called with the same transaction as the state change. */
  insert(event: NewOutboxEvent): Promise<bigint>;

  /** Write many in one statement. See the implementation for the parameter ceiling. */
  insertMany(events: readonly NewOutboxEvent[]): Promise<bigint[]>;

  /**
   * Claim up to `limit` unpublished events for this relay instance.
   *
   * **Must be called inside a transaction.** The claim is held by row locks
   * that only exist until the transaction ends; outside one, every relay
   * instance claims the same rows and every event is published N times.
   */
  claimBatch(limit: number): Promise<OutboxRecord[]>;

  /** Mark claimed events published, recording where they landed. */
  markPublished(outcomes: readonly PublishOutcome[]): Promise<void>;

  /**
   * Record a failed publish attempt.
   *
   * Increments `attempts` rather than deleting, so a permanently failing event
   * is visible in a query instead of vanishing. A relay that silently drops
   * what it cannot publish is worse than one that stalls.
   */
  markFailed(id: bigint, error: string): Promise<void>;

  /** Remove published rows older than `cutoff`. Returns the number deleted. */
  deletePublishedBefore(cutoff: Date, limit: number): Promise<number>;

  /**
   * How many events are waiting.
   *
   * This is the outbox's lag metric and the single most important alert on the
   * relay: a rising count means events are being written faster than published,
   * and every one of them is a state change the rest of the system has not
   * heard about yet.
   */
  countUnpublished(): Promise<number>;

  /** Events for one aggregate, oldest first. For support and debugging. */
  findByAggregate(
    aggregateType: string,
    aggregateId: string,
    limit: number,
  ): Promise<OutboxRecord[]>;
}
